baseurl: https://panggahdputra.com/
title: Panggah D. Putra
theme: hugo-creative-portfolio-theme
languageCode: en-us
disqusShortname: ''
googleAnalytics: '305620212'
params:
  sidebarAbout:
    - Selamat datang di panggahdputra.com.
    - Website pribadi ini berisi dokumentasi hasil saya belajar R, visualisasi data dengan R, R Markdown, blogdown, dan lain-lain.
  navlinks:
    - home: yes
      name: Galeri
      url: galeri/
    - name: Katalog
      url: katalog/
    - name: Artikel
      url: artikel/
    - name: Tentang
      url: about/
  social:
    github: https://github.com/panggahdputra
  copyright: '&copy;2022 Panggah D. Putra'
  style: blue
